project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Version in es"
  - name: en
    text: "Version in en"
  mainlanguage: 'en'
  languages: ['es']
title-es: title in es
title-fr: title in fr
description-es: description in es
author-es: author in es
lang: en
